const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || '0.0.0.0';
const ROOT = __dirname;
const PUBLIC = path.join(ROOT, 'public');
const DATA_DIR = process.env.DATA_DIR || path.join(ROOT, 'data');
const DB_FILE = process.env.DB_FILE || path.join(DATA_DIR, 'bloodbridge.db');
const FRONTEND_ORIGIN = process.env.FRONTEND_ORIGIN || '*';
fs.mkdirSync(DATA_DIR, { recursive: true });
const db = new DatabaseSync(DB_FILE);
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS donors(id TEXT PRIMARY KEY,name TEXT NOT NULL,blood_group TEXT NOT NULL,phone TEXT NOT NULL,location TEXT NOT NULL,eligibility TEXT NOT NULL DEFAULT 'Pending Verification',availability TEXT NOT NULL DEFAULT 'Available',last_donation TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS inventory(id TEXT PRIMARY KEY,blood_group TEXT NOT NULL,location TEXT NOT NULL,available_units INTEGER NOT NULL,reserved_units INTEGER NOT NULL DEFAULT 0,threshold_units INTEGER NOT NULL,expiry_days INTEGER NOT NULL,component TEXT NOT NULL DEFAULT 'Whole Blood',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS emergency_requests(id TEXT PRIMARY KEY,patient_name TEXT NOT NULL,blood_group TEXT NOT NULL,units INTEGER NOT NULL,urgency TEXT NOT NULL,hospital TEXT NOT NULL,location TEXT NOT NULL,note TEXT,status TEXT NOT NULL DEFAULT 'AI MATCHING',distance TEXT DEFAULT 'Calculating',eta TEXT DEFAULT 'Calculating',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,icon TEXT NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,time_label TEXT NOT NULL,type TEXT NOT NULL,is_read INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY,time_label TEXT NOT NULL,actor TEXT NOT NULL,role TEXT NOT NULL,action TEXT NOT NULL,resource TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,phone TEXT NOT NULL,role TEXT NOT NULL,expires_at INTEGER NOT NULL);`);

const uid=p=>`${p}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;
const timeLabel=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const safe=(v,max=500)=>String(v??'').trim().slice(0,max);
const groups=new Set(['A+','A−','B+','B−','AB+','AB−','O+','O−']);
function audit(actor,role,action,resource,status='Success'){db.prepare('INSERT INTO audit_logs(id,time_label,actor,role,action,resource,status) VALUES(?,?,?,?,?,?,?)').run(uid('AUD'),timeLabel(),actor,role,action,resource,status);}
function seed(){
 if(db.prepare('SELECT COUNT(*) n FROM inventory').get().n===0){const s=db.prepare("INSERT INTO inventory(id,blood_group,location,available_units,reserved_units,threshold_units,expiry_days,component,updated_at) VALUES(?,?,?,?,?,?,?,'Whole Blood',CURRENT_TIMESTAMP)");for(const r of [['INV-A-P','A+','Delhi',2184,120,500,24],['INV-A-N','A−','Noida',624,54,250,12],['INV-B-P','B+','Delhi',1982,108,450,20],['INV-B-N','B−','Noida',318,42,180,8],['INV-AB-P','AB+','Gurugram',706,32,180,14],['INV-AB-N','AB−','Delhi',112,19,100,5],['INV-O-P','O+','Delhi',4512,270,700,22],['INV-O-N','O−','Noida',42,11,100,4]])s.run(...r)}
 if(db.prepare('SELECT COUNT(*) n FROM donors').get().n===0){const s=db.prepare('INSERT INTO donors(id,name,blood_group,phone,location,eligibility,availability,last_donation) VALUES(?,?,?,?,?,?,?,?)');for(const r of [['Aarav Sharma','O+','98765 10001','Delhi','Eligible','Available','12 Jul 2026'],['Priya Verma','O−','98765 10002','Noida','Eligible','Available','03 Jul 2026'],['Rahul Singh','A+','98765 10003','Delhi','Eligible','Available','28 Jun 2026'],['Neha Kapoor','B+','98765 10004','Gurugram','Eligible','Available','16 Jul 2026'],['Vikram Mehta','AB+','98765 10005','Delhi','Eligible','Available','01 Jul 2026'],['Ananya Gupta','B−','98765 10006','Noida','Eligible','On Call','18 Jun 2026'],['Rohan Jain','A−','98765 10007','Delhi','Eligible','Available','09 Jul 2026'],['Sneha Rao','O+','98765 10008','Gurugram','Eligible','Available','14 Jul 2026']])s.run(uid('DON'),...r)}
 if(db.prepare('SELECT COUNT(*) n FROM emergency_requests').get().n===0){const s=db.prepare('INSERT INTO emergency_requests(id,patient_name,blood_group,units,urgency,hospital,location,note,status,distance,eta) VALUES(?,?,?,?,?,?,?,?,?,?,?)');for(const r of [['REQ-20481','Emergency Patient','O−',2,'CRITICAL','New Delhi Emergency Hospital','New Delhi','Emergency','AI MATCHING','4.8 km','12 min'],['REQ-20480','Emergency Patient','A+',3,'HIGH','City Care Hospital','Delhi','Emergency','MATCH FOUND','6.2 km','18 min'],['REQ-20479','Emergency Patient','B−',2,'CRITICAL','Metro Medical Centre','Noida','Emergency','AI MATCHING','9.1 km','24 min']])s.run(...r)}
 if(db.prepare('SELECT COUNT(*) n FROM notifications').get().n===0){const s=db.prepare('INSERT INTO notifications(id,icon,title,message,time_label,type) VALUES(?,?,?,?,?,?)');for(const r of [['🔴','Critical Blood Request','O− required at City Hospital.','2 min ago','critical'],['🟠','Inventory Alert','14 O− units approaching expiry.','8 min ago','warn'],['🟢','Match Confirmed','Blood Bank confirmed 2 units.','12 min ago','ok'],['🔵','New Donor Available','Eligible donor found within 5 km.','16 min ago','info']])s.run(uid('NOT'),...r)}
 if(db.prepare('SELECT COUNT(*) n FROM audit_logs').get().n===0){const s=db.prepare('INSERT INTO audit_logs(id,time_label,actor,role,action,resource,status) VALUES(?,?,?,?,?,?,?)');for(const r of [['19:24','System','AI Engine','Matched REQ-20481','REQ-20481','Success'],['19:23','City Blood Centre','Blood Bank','Confirmed O− units','INV-O-204','Success'],['19:22','Admin','Admin','Created emergency request','REQ-20481','Success'],['19:20','System','Notification','Broadcast donor alert','BCAST-981','Success']])s.run(uid('AUD'),...r)}
}
seed();
const clients=new Set();
function emit(event,payload){const msg=`event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`;for(const res of clients){try{res.write(msg)}catch{}}}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>300000){req.destroy();reject(new Error('Payload too large'))}});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)})}
function send(res,status,data,type='application/json'){const raw=type==='application/json'?JSON.stringify(data):data;res.writeHead(status,{'Content-Type':type,'Access-Control-Allow-Origin':FRONTEND_ORIGIN,'Cache-Control':type==='application/json'?'no-store':'no-cache'});res.end(raw)}
function auth(){return true}
function compatible(p,d){const pa=p.replace(/[+−]/,''),da=d.replace(/[+−]/,''),pr=p.endsWith('+'),dr=d.endsWith('+');const abo=pa==='O'?da==='O':pa==='A'?['A','O'].includes(da):pa==='B'?['B','O'].includes(da):['A','B','AB','O'].includes(da);return abo&&(pr||!dr)}
function componentScore(c){return c==='Whole Blood'?1:c.includes('RBC')?.95:c==='Platelets'?.9:c.includes('FFP')?.88:.8}

async function api(req,res,url){
 const method=req.method, p=url.pathname, q=url.searchParams;
 try{
  if(p==='/api/health'&&method==='GET')return send(res,200,{ok:true,service:'BloodBridge API',database:'SQLite',time:new Date().toISOString()});
  if(p==='/api/config'&&method==='GET')return send(res,200,{googleMapsApiKey:process.env.GOOGLE_MAPS_API_KEY||''});
  if(p==='/api/bootstrap'&&method==='GET')return send(res,200,{donors:db.prepare('SELECT * FROM donors ORDER BY created_at DESC').all(),inventory:db.prepare('SELECT * FROM inventory ORDER BY blood_group').all(),requests:db.prepare('SELECT * FROM emergency_requests ORDER BY created_at DESC').all(),notifications:db.prepare('SELECT * FROM notifications ORDER BY created_at DESC LIMIT 50').all(),audit:db.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 100').all()});
  if(p==='/api/donors'&&method==='GET'){let r=db.prepare('SELECT * FROM donors ORDER BY created_at DESC').all(),x=safe(q.get('q'),100).toLowerCase(),g=safe(q.get('group'),20);if(x)r=r.filter(d=>JSON.stringify(d).toLowerCase().includes(x));if(g&&g!=='All Groups')r=r.filter(d=>d.blood_group===g);return send(res,200,r)}
  if(p==='/api/donors'&&method==='POST'){const b=await body(req),name=safe(b.name,100),g=safe(b.group,5),phone=safe(b.phone,30),loc=safe(b.location,100);if(!name||!groups.has(g)||!phone||!loc)return send(res,400,{error:'Name, valid blood group, phone and location are required.'});if(!/^[+()\-\s\d]{7,20}$/.test(phone))return send(res,400,{error:'Enter a valid phone number.'});const id=uid('DON');db.prepare('INSERT INTO donors(id,name,blood_group,phone,location,eligibility,availability,last_donation) VALUES(?,?,?,?,?,?,?,?)').run(id,name,g,phone,loc,'Pending Verification',safe(b.availability,30)||'Available',safe(b.lastDonation,50)||'Not provided');audit('Admin','Admin','Registered donor',id);emit('donor.created',{id});return send(res,201,{id,message:`${name} registered successfully`,donor:db.prepare('SELECT * FROM donors WHERE id=?').get(id)})}
  if(p==='/api/inventory'&&method==='GET'){let r=db.prepare('SELECT * FROM inventory ORDER BY blood_group').all(),g=safe(q.get('group'),20),l=safe(q.get('location'),50);if(g&&g!=='All Blood Groups')r=r.filter(x=>x.blood_group===g);if(l&&l!=='All Locations')r=r.filter(x=>x.location===l);return send(res,200,r)}
  if(p==='/api/inventory/export'&&method==='GET'){const r=db.prepare('SELECT blood_group,location,available_units,reserved_units,threshold_units,expiry_days,component,updated_at FROM inventory ORDER BY blood_group').all();const csv=['Blood Group,Location,Available Units,Reserved Units,Threshold,Expiry Days,Component,Updated At',...r.map(x=>[x.blood_group,x.location,x.available_units,x.reserved_units,x.threshold_units,x.expiry_days,x.component,x.updated_at].join(','))].join('\n');res.writeHead(200,{'Content-Type':'text/csv','Content-Disposition':'attachment; filename="bloodbridge-inventory.csv"','Access-Control-Allow-Origin':FRONTEND_ORIGIN});return res.end(csv)}
  if(p==='/api/requests'&&method==='GET'){let r=db.prepare('SELECT * FROM emergency_requests ORDER BY created_at DESC').all(),u=safe(q.get('urgency'),20),s=safe(q.get('status'),40);if(u&&u!=='All Urgency')r=r.filter(x=>x.urgency===u);if(s&&s!=='All Status')r=r.filter(x=>x.status===s);return send(res,200,r)}
  if(p==='/api/requests'&&method==='POST'){const b=await body(req),patientName=safe(b.patientName,100),g=safe(b.group,5),units=Number(b.units),u=safe(b.urgency,20).toUpperCase(),hospital=safe(b.hospital,150),loc=safe(b.location,100);if(!patientName||!groups.has(g)||!Number.isInteger(units)||units<1||units>100||!hospital||!loc)return send(res,400,{error:'Patient name, valid blood group, hospital, location and units between 1 and 100 are required.'});const id=uid('REQ');db.prepare('INSERT INTO emergency_requests(id,patient_name,blood_group,units,urgency,hospital,location,note,status,distance,eta) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,patientName,g,units,u,hospital,loc,safe(b.note,500),'AI MATCHING','Calculating','Calculating');db.prepare('INSERT INTO notifications(id,icon,title,message,time_label,type) VALUES(?,?,?,?,?,?)').run(uid('NOT'),'🔴','Emergency Blood Request',`${g} required at ${hospital}. Broadcast queued for verified responders.`,'Just now','critical');audit('Admin','Admin','Created emergency request',id);emit('request.created',{id});return send(res,201,{id,request:db.prepare('SELECT * FROM emergency_requests WHERE id=?').get(id)})}
  if(p==='/api/requests/broadcast'&&method==='POST'){const r=db.prepare("UPDATE emergency_requests SET status='MATCH FOUND',distance=CASE WHEN distance='Calculating' THEN '4.8 km' ELSE distance END,eta=CASE WHEN eta='Calculating' THEN '12 min' ELSE eta END WHERE status='AI MATCHING'").run();audit('System','Notification','Broadcast pending emergency requests','BROADCAST');emit('requests.broadcast',{count:r.changes});return send(res,200,{ok:true,updated:r.changes})}
  if(p==='/api/ai/match'&&method==='POST'){const b=await body(req),patient=safe(b.patientABO,3)+(safe(b.patientRh,10)==='Positive'?'+':'−'),units=Math.max(1,Math.min(100,Number(b.units)||1)),component=safe(b.component,60)||'Whole Blood',ig=safe(b.inventoryGroup,100);if(!groups.has(patient))return send(res,400,{error:'Invalid patient blood group.'});let inv=db.prepare('SELECT * FROM inventory').all();if(ig&&ig!=='Auto-select from compatible inventory')inv=inv.filter(x=>x.blood_group===ig);const donors=db.prepare("SELECT * FROM donors WHERE eligibility='Eligible' AND availability IN ('Available','On Call')").all();const candidates=inv.map(i=>{const clinical=compatible(patient,i.blood_group),cs=componentScore(component),is=Math.min(1,i.available_units/Math.max(units*10,i.threshold_units)),d=donors.find(x=>x.blood_group===i.blood_group)||donors[0];const score=clinical?Math.min(100,34+10+10+8*cs+8+5+5+9+7*is):Math.min(100,18+7*is);return {group:i.blood_group,inventory:i.available_units,clinical,score,componentScore:cs,donor:d?{name:d.name,location:d.location}:null,factors:{abo:clinical?1:0,rh:clinical?1:0,component:cs,inventory:is}}}).sort((a,b)=>Number(b.clinical)-Number(a.clinical)||b.score-a.score);const best=candidates.find(x=>x.clinical)||candidates[0]||null;audit('System','AI Engine','Generated blood match ranking',`AI-${Date.now()}`);emit('ai.completed',{patient});return send(res,200,{patient,units,component,candidates,best,recommendation:best&&best.clinical?`Top compatible candidate: ${best.group}`:'No clinically compatible candidate in current inventory'})}
  if(p==='/api/notifications'&&method==='GET')return send(res,200,db.prepare('SELECT * FROM notifications ORDER BY created_at DESC LIMIT 50').all());
  if(p==='/api/notifications/read-all'&&method==='POST'){db.prepare('UPDATE notifications SET is_read=1').run();audit('Admin','Notification','Marked all notifications as read','NOTIFICATIONS');emit('notifications.readAll',{});return send(res,200,{ok:true})}
  if(p==='/api/audit'&&method==='GET')return send(res,200,db.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 100').all());
  if(p==='/api/search'&&method==='GET'){const x=safe(q.get('q'),100).toLowerCase();if(!x)return send(res,200,{donors:[],requests:[],inventory:[]});const match=r=>r.filter(v=>JSON.stringify(v).toLowerCase().includes(x));return send(res,200,{donors:match(db.prepare('SELECT id,name,blood_group,location,phone FROM donors').all()),requests:match(db.prepare('SELECT id,patient_name,blood_group,hospital,location,status FROM emergency_requests').all()),inventory:match(db.prepare('SELECT id,blood_group,location,available_units FROM inventory').all())})}
  if(p==='/api/auth/send-otp'&&method==='POST'){const b=await body(req),phone=safe(b.phone,30);if(!/^[+()\-\s\d]{7,20}$/.test(phone))return send(res,400,{error:'Enter a valid phone number.'});audit('System','Auth','OTP requested',phone);return send(res,200,{ok:true,demo:true,otp:process.env.NODE_ENV==='production'?undefined:(process.env.DEMO_OTP||'123456'),message:'Demo OTP generated. Configure a real OTP provider for production.'})}
  if(p==='/api/auth/verify'&&method==='POST'){const b=await body(req),phone=safe(b.phone,30),otp=safe(b.otp,10),expected=process.env.DEMO_OTP||'123456';if(otp!==expected)return send(res,401,{error:'Invalid OTP.'});const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions(token,phone,role,expires_at) VALUES(?,?,?,?)').run(token,phone,'ADMIN',Date.now()+8*60*60*1000);audit('Admin','Auth','Logged in',phone);return send(res,200,{ok:true,token,role:'ADMIN'})}
  if(p==='/api/events'&&method==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','Access-Control-Allow-Origin':FRONTEND_ORIGIN});res.write(`event: ready\ndata: ${JSON.stringify({time:new Date().toISOString()})}\n\n`);clients.add(res);const hb=setInterval(()=>{try{res.write(': heartbeat\n\n')}catch{}},25000);req.on('close',()=>{clearInterval(hb);clients.delete(res)});return}
  return false;
 }catch(e){console.error(e);return send(res,500,{error:'Server error',detail:process.env.NODE_ENV==='production'?'Unexpected server error':e.message})}
}

const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);res.setHeader('Access-Control-Allow-Origin',FRONTEND_ORIGIN);res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.writeHead(204).end();if(url.pathname.startsWith('/api/')){const handled=await api(req,res,url);if(handled!==false)return;}let file=url.pathname==='/'?path.join(PUBLIC,'index.html'):path.normalize(path.join(PUBLIC,url.pathname));if(!file.startsWith(PUBLIC))return send(res,403,{error:'Forbidden'});if(fs.existsSync(file)&&fs.statSync(file).isFile()){res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});return fs.createReadStream(file).pipe(res)}if(!url.pathname.startsWith('/api/')){res.writeHead(200,{'Content-Type':mime['.html']});return fs.createReadStream(path.join(PUBLIC,'index.html')).pipe(res)}send(res,404,{error:'Not found'})});
server.listen(PORT,HOST,()=>console.log(`BloodBridge full-stack server running on http://localhost:${PORT}`));
process.on('SIGINT',()=>{db.close();process.exit(0)});process.on('SIGTERM',()=>{db.close();process.exit(0)});
